version: 0.2

phases: 
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Running install phase"
  pre_build:
    commands: 
      - echo "Running pre_build phase"
      - echo "Removing existing build"
      - aws s3 ls s3://www.nigelaukland.com
      - aws s3 rm s3://www.nigelaukland.com/* --recursive
      - aws s3 ls s3://www.nigelaukland.com
  build:
    commands:
      - echo "Running build phase"
      - ls dist/index.html
      - cd dist
      - ls
  post_build:
    commands:
      - echo "Running post_build phase"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'